#include "songs.h"
#include "chords.h"
#include "audio.h"
#include "audioConfig.h"
#include "keyboard.h"
#include "timing.h"

void write_printf(const char *text)
{
    while (*text)
    {
        putchar(*text);
        fflush(stdout);
        sleep_ms(60);
        text++;
    }
}

#include <stdio.h>

void print_harmony(void) {
    printf(
"\n"
"                    ♪        ♫\n"
"                 .-=========-.\n"
"               .'  .-\"\"\"\"-.   '.\n"
"              /   /  o  o  \\    \\\n"
"             |   |     ^    |    |\n"
"             |   |   \\___/  |    |\n"
"             |    \\  _____ /     |\n"
"          .--|------|_|_|_|------|--.\n"
"         /   |      | ♪ ♪ |      |   \\\n"
"        /    |      |_____|      |    \\\n"
"       /     |   .-<_____->-.    |     \\\n"
"      /      |  /  /|   |\\  \\    |      \\\n"
"     /_______|_/__/ |___| \\__\\___|_______\\\n"
"              /_/   /___\\   \\_\\\n"
"             /_/   /_/ \\_\\   \\_\\\n"
"\n"
"      ======================================\n"
"                H A R M O N Y\n"
"            Your Music Synthesis mentor\n"
"      ======================================\n"
"             ♪   Learn • Create • Play   ♫\n"
"\n"
    );
}

void wait_for_user()
{
    // flushInputBuffer();
    printf("Hit any key to continue...\n\n");
    getchar();
}

void soundImprovementDemo()
{
    ENABLE_DELAY=0;
    ENABLE_HARMONIES = 0;
    ENABLE_ENVELOPE = 0;
    ENABLE_HAMMER = 0;
    SHOW_KEYBOARD = 0;
    flushInputBuffer();
    print_harmony();
    write_printf("\nHi I am Harmony, your new sound synthesis mentor...\n");
    sleep_ms(500);
    write_printf("\nToday we are gonna have a look at creation of sound on computer...\n");
    sleep_ms(500);
    wait_for_user();
    
    write_printf("First, let's see some simple C4 note...\n");
    wait_for_user();
    playNoteMs(C4, 1000);
    sleep_ms(1000);
    wait_for_user();

    write_printf("Now let's combine several notes into C major chord...\n");
    wait_for_user();
    c_major_chord();
    wait_for_user();

    write_printf("Well, the sound is still a bit too artificial. What if we add some harmonies. First the original sound:\n");
    wait_for_user();
    playNoteMs(C4, 1000);
    sleep_ms(1200);
    write_printf("And now with the harmonies:\n");
    wait_for_user();
    ENABLE_HARMONIES = 1;
    playNoteMs(C4, 1000);
    sleep_ms(1000);
    wait_for_user();

    write_printf("That was much better. But does it sound like a piano?\n");
    write_printf("I am just a program, but to me it sounds like an organs...\n");
    write_printf("The problem is that unlike in organs, the sound in piano is generated by hammer hitting the strings...\n");
    write_printf("That creates strong sound at the beginning that quickly falls in volume and then slowly decays... We call this 'envelope'\n");
    write_printf("Let's see how it sounds\n");
    wait_for_user();
    ENABLE_ENVELOPE = 1;
    playNoteMs(C4, 4000);
    wait_for_user();

    write_printf("Wow, making progres... But something is still missing...\n");
    write_printf("The one missing step is adding some echo... In the real piano sound resonates in the piano cabinet...\n");
    write_printf("So let's add that...\n");
    wait_for_user();
    ENABLE_DELAY=1;
    ENABLE_HAMMER = 1;
    playNoteMs(C4, 4000);
    sleep_ms(1000);
    wait_for_user();

    write_printf("Pretty good. But why have a synthetizer just for playing single notes...\n");
    write_printf("Let's play some song ♪...\n");
    wait_for_user();
    ode_to_joy();
    wait_for_user();

    write_printf("And now lets add several overlaping notes ♪...\n");
    wait_for_user();
    ode_to_joy2();
    wait_for_user();

    write_printf("That would be everything from my part.\n");
    write_printf("I hope you have enjoyed this walk-through and that you will check out other songs as well...\n");
    write_printf("Have fun!\n");
    wait_for_user();


    // octave();
    // ode_to_joy1();
    // ode_to_joy2();
    // my_heart_will_go_on();
    // my_heart_will_go_on_low();
    // hedwigs_theme();
    SHOW_KEYBOARD = 1;
}